[package]
name = "mini-dioxus-core"
version = "0.1.0"
authors = ["7213"]
edition = "2018"
description = "模仿 rust 实现的 dioxus"
license = "MIT OR Apache-2.0"
keywords = ["dom", "ui", "gui", "react", "wasm"]

[lib]
