[package]
name = "rreact-core"
version = "0.1.0"
authors = ["7213"]
edition = "2018"
description = "rust impl react-like"
license = "MIT OR Apache-2.0"
keywords = ["dom", "ui", "gui", "react", "wasm"]

[lib]
